import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Header from '../components/header';
import { ThemeProvider } from '@/provider/theme-provider';
import { ModeToggle } from '@/components/theme-mode-toggle';
import  ActiveSectionContextProvider from '../../context/active-section-context';
import { Toaster } from '@/components/ui/toaster';
import { Analytics } from "@vercel/analytics/react"
import BackToTopButton from '@/components/back-to-top-button';

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Franco | Portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en" className='!scroll-smooth'>
      <body className={ `${montserrat.className} bg-[#dad5ab6a] text-gray-950 `}>
{/*       <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > */}
        {/* <div className="bg-[#7144466b] absolute top-[-6rem] -z-10 right-[5rem] h-[31.25rem] w-[31.25rem] rounded-full blur-[10rem] sm:w-[68.75rem] dark:bg-[#946263]"></div> */}
        {/* <div className="bg-[#517b8d5c] absolute top-[-1rem] -z-10 left-[-35rem] h-[31.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] dark:bg-[#676394]"></div> */}
        <ActiveSectionContextProvider>
          <Header/>
          {children}
          <BackToTopButton/>
        </ActiveSectionContextProvider>

        {/* <div className='fixed bottom-2 left-2'>
          <ModeToggle/>
        </div> */}
        <Toaster />
   
{/*         </ThemeProvider>
         */}
         <Analytics/>
        </body>
    </html>
  )
}
